name: Android Release

on:
  push


jobs:

  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11.0
        uses: actions/setup-java@v1
        with:
          java-version: 11.0

      - name: Run Unit Tests
        run: bash ./gradlew test --stacktrace

  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11.0
        uses: actions/setup-java@v1
        with:
          java-version: 11.0

      - name: Assemble debug APP APK
        run: bash ./gradlew assembleDebug --stacktrace
        env:
          ZTM_API_KEY: ${{ secrets.ZTM_API_KEY }}

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Android UI Tests
        run: bash ./gradlew assembleDebugAndroidTest
        env:
          ZTM_API_KEY: ${{ secrets.ZTM_API_KEY }}

      - name: Upload Android Test APK
        uses: actions/upload-artifact@v1
        with:
          name: app-debug-androidTest
          path: app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk

  firebase:
    name: Run ui tests with firebase test lab
    needs: apk
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Download apk
        uses: actions/download-artifact@v1
        with:
          name: app-debug-androidTest


    permissions:
      contents: 'read'
      id-token: 'write'

      - uses: 'actions/checkout@v3'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'principalSet://iam.googleapis.com/projects/147543835481/locations/global/workloadIdentityPools/githubactions/*'
          service_account: 'github-action@actions-378217.iam.gserviceaccount.com'

      - name: set Current project
        run: gcloud config set project 'action-e8475'

      - name: Run Instrumentation Tests in Firebase Test Lab
        run: gcloud firebase test android run --type instrumentation --app app-debug/app-debug.apk --test app-debug-androidTest/app-debug-androidTest.apk --device model=Pixel5,version=28,locale=pl,orientation=portrait
