name: Android Release

on:
  push


jobs:

  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11.0
        uses: actions/setup-java@v1
        with:
          java-version: 11.0

      - name: Run Unit Tests
        run: bash ./gradlew test --stacktrace

  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11.0
        uses: actions/setup-java@v1
        with:
          java-version: 11.0

      - name: Assemble debug APP APK
        run: bash ./gradlew assembleDebug --stacktrace
        env:
          ZTM_API_KEY: ${{ secrets.ZTM_API_KEY }}

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Android UI Tests
        run: bash ./gradlew assembleDebugAndroidTest
        env:
          ZTM_API_KEY: ${{ secrets.ZTM_API_KEY }}

      - name: Upload Android Test APK
        uses: actions/upload-artifact@v1
        with:
          name: app-debug-androidTest
          path: app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk

  firebase:
    name: Run ui tests with firebase test lab
    needs: apk
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v1

      - name: Download apk
        uses: actions/download-artifact@v1
        with:
          name: app-debug-androidTest

      - uses: 'actions/checkout@v3'


      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: action-e8475
          service_account_key: ${{ secrets.FB_KEY }}
          export_default_credentials: true

      - name: Run Instrumentation Tests in Firebase Test Lab
        run: |
          gcloud firebase test android run --type instrumentation --app app/build/outputs/apk/debug/app-debug.apk --test app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
